CREATE DATABASE agenda DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE contatos (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
	telefone VARCHAR(15) DEFAULT NULL,
    PRIMARY KEY(id)
);